nombre = input("Cual es tu nombre? ")
apellido = input("Cual es tu apellido? ")
seccion = input("Cual es tu seccion? ")
sede = input("Cual es tu sede? ")
print("Hola " + nombre, apellido + "! Tu seccion es "+ seccion +" y tu sede es "+ sede)
